/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DsBadge: typeof import('./../app/components/ds/badge/DsBadge.vue')['default']
    DsButton: typeof import('./../app/components/ds/button/DsButton.vue')['default']
    DsCard: typeof import('./../app/components/ds/card/DsCard.vue')['default']
    DsStack: typeof import('./../app/components/ds/stack/DsStack.vue')['default']
    DsToggle: typeof import('./../app/components/ds/toggle/DsToggle.vue')['default']
    FieldNumber: typeof import('./../app/components/ds/field/FieldNumber.vue')['default']
    FieldSelect: typeof import('./../app/components/ds/field/FieldSelect.vue')['default']
    FieldText: typeof import('./../app/components/ds/field/FieldText.vue')['default']
    FieldWrapper: typeof import('./../app/components/ds/field/FieldWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
